<!--
SPDX-FileCopyrightText: 2022 Zextras <https://www.zextras.com>

SPDX-License-Identifier: AGPL-3.0-only
-->

<project xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xmlns="http://maven.apache.org/POM/4.0.0"
  xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/maven-v4_0_0.xsd">
  <artifactId>carbonio-user-management-sdk</artifactId>
  <build>
    <plugins>
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-compiler-plugin</artifactId>
        <version>3.13.0</version>
      </plugin>
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-surefire-plugin</artifactId>
        <version>3.2.5</version>
        <configuration>
          <useModulePath>false</useModulePath>
        </configuration>
      </plugin>
    </plugins>
    <sourceDirectory>src/main/java</sourceDirectory>
  </build>
  <dependencies>
    <dependency>
      <artifactId>guice</artifactId>
      <groupId>com.google.inject</groupId>
      <version>${guice.version}</version>
    </dependency>

    <dependency>
      <artifactId>httpclient</artifactId>
      <groupId>org.apache.httpcomponents</groupId>
      <version>${apache-httpclient.version}</version>
    </dependency>

    <dependency>
      <artifactId>jackson-databind</artifactId>
      <groupId>com.fasterxml.jackson.core</groupId>
      <version>${jackson.version}</version>
    </dependency>

    <dependency>
      <artifactId>commons-io</artifactId>
      <groupId>commons-io</groupId>
      <version>${apache-common.version}</version>
    </dependency>

    <dependency>
      <artifactId>vavr</artifactId>
      <groupId>io.vavr</groupId>
      <version>${vavr.version}</version>
    </dependency>

    <dependency>
      <groupId>org.junit.jupiter</groupId>
      <artifactId>junit-jupiter</artifactId>
      <version>${junit-jupiter.version}</version>
      <scope>test</scope>
    </dependency>
    <dependency>
      <groupId>org.testcontainers</groupId>
      <artifactId>junit-jupiter</artifactId>
      <version>${testcontainers.version}</version>
      <scope>test</scope>
    </dependency>
    <dependency>
      <groupId>org.testcontainers</groupId>
      <artifactId>testcontainers</artifactId>
      <version>${testcontainers.version}</version>
      <scope>test</scope>
    </dependency>
    <dependency>
      <groupId>com.github.tomakehurst</groupId>
      <artifactId>wiremock-jre8</artifactId>
      <version>${wiremock.version}</version>
      <scope>test</scope>
    </dependency>

  </dependencies>
  <distributionManagement>
    <repository>
      <id>artifactory</id>
      <name>Zextras releases</name>
      <url>https://zextras.jfrog.io/artifactory/public-maven-repo</url>
    </repository>
  </distributionManagement>
  <groupId>com.zextras.carbonio.user-management</groupId>
  <modelVersion>4.0.0</modelVersion>

  <name>carbonio-user-management-sdk</name>

  <packaging>jar</packaging>

  <properties>
    <maven.compiler.source>17</maven.compiler.source>
    <maven.compiler.target>17</maven.compiler.target>
    <maven.version.ignore>(?i).*-(alpha|beta|m|rc)([-.]?\d+)?</maven.version.ignore>
    <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    <apache-common.version>2.20.0</apache-common.version>
    <apache-httpclient.version>4.5.14</apache-httpclient.version>
    <guice.version>7.0.0</guice.version>
    <jackson.version>2.19.2</jackson.version>
    <vavr.version>0.10.7</vavr.version>
    <junit-jupiter.version>5.12.1</junit-jupiter.version>
    <testcontainers.version>1.21.3</testcontainers.version>
    <wiremock.version>2.35.1</wiremock.version>
  </properties>

  <version>0.5.5</version>

</project>
